SELECT [Sta3n]
      ,[Sta3nName]
      ,[VISNPreFY15]
      ,[VISNFY16]
      ,[VISNFY17]
      ,[Active]
      ,[NextSta3n]
      ,[TimeZone]
      ,[SiteCode]
      ,[RegionFY15]
      ,[DistrictNameFY16]
      ,[DistrictNumberFY16]
      ,[DistrictNameFY17]
      ,[DistrictNumberFY17]
      ,[City]
      ,[StateSID]
  FROM [CDWWork].[Dim].[Sta3n]
