/*
|--------------------------------------------------------------------------------
| insert_Spatient_Spatient.sql
|--------------------------------------------------------------------------------
*/

-- Set the active database
USE CDWWork;
GO

-- Insert data into the SPatient.SPatient table
INSERT INTO SPatient.SPatient
(
  PatientSID, PatientIEN, Sta3n, PatientName, PatientLastName, PatientFirstName, TestPatientFlag, CDWPossibleTestPatientFlag, VeteranFlag, PatientType, PatientTypeSID, PatientICN, ScrSSN, PatientSSN, PseudoSSNReason, SSNVerificationStatus, GovernmentEmployeeFlag, SensitiveFlag, Age, BirthDateTime, BirthVistaErrorDate, BirthDateTimeTransformSID, DeceasedFlag, DeathDateTime, DeathVistaErrorDate, DeathDateTimeTransformSID, DeathEnteredByStaffSID, DeathNotificationSource, DeathDocumentationType, DeathModifiedDateTime, DeathModifiedVistaErrorDate, DeathModifiedDateTimeTransformSID, DeathLastUpdatedByStaffSID, Gender, SelfIdentifiedGender, Religion, ReligionSID, MaritalStatus, MaritalStatusSID, CollateralSponsorPatientSID, CurrentEnrollmentSID, MeansTestStatus, CurrentMeansTestStatusSID, PeriodOfService, PeriodOfServiceSID, OperationDesertShieldRank, ODSRankType, ODSRecalledCode, ODSTreatmentDateTime, ODSTreatmentVistaErrorDate, ODSTreatmentDateTimeTransformSID, FederalAgencySID, FilipinoVeteranCode, ServiceConnectedFlag, Eligibility, EligibilityVACode, EligibilitySID, EligibilityStatus, EligibilityStatusDateTime, EligibilityStatusVistaErrorDate, EligibilityStatusDateTimeTransformSID, EligibilityVerificationSource, EligibilityVerificationMethod, EligibilityInterimDateTime, EligibilityInterimVistaErrorDate, EligibilityInterimDateTimeTransformSID, EligibilityEnteredStaffSID, IneligibleReason, IneligibleVAROReason, IneligibleCity, IneligibleStateSID, IneligibleDateTime, IneligibleVistaErrorDate, IneligibleDateTimeTransformSID, IneligibleSource, PatientMissingSource, PatientMissingDateTime, PatientMissingVistaErrorDate, PatientMissingDateTimeTransformSID, PatientMissingCity, PatientMissingStateSID, FugitiveFelonFlag, FFFEnteredDateTime, FFFEnteredVistaErrorDate, FFFEnteredDateTimeTransformSID, FFFEnteredStaffSID, FFFRemovedReason, FFFRemovedDateTime, FFFRemovedVistaErrorDate, FFFRemovedDateTimeTransformSID, FFFRemovedStaffSID, PatientEnteredByStaffSID, PatientEnteredCode, PatientEnteredRemark, PatientEnteredDateTime, PatientEnteredVistaErrorDate, PatientEnteredDateTimeTransformSID, DuplicateRecordStatus, DestinationMergePatientSID, PreferredInstitutionSID, PreferredInstitutionSource, EmergencyResponseIndicator, InsuranceCoverageFlag, MedicaidEligibleFlag, MedicaidNumber, MedicaidInquireDateTime, MedicaidInquireVistaErrorDate, MedicaidInquireDateTimeTransformSID, VeteranTransportationProgramFlag
)
VALUES
(110011001, 'IEN100001', 508, 'Adam Dooree', 'Dooree', 'Adam', 'N', 'N', 'Y', 'Regular', 101, 'ICN100001', '123456789', '123456789', 'None', 'Verified', 'N', 'N', 45, '1980-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'M', 'Male', 'Christian', 1, 'Single', 1, NULL, 1001, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(110011002, 'IEN100002', 508, 'Barry Miifaa', 'Miifaa', 'Barry', 'N', 'N', 'Y', 'Regular', 101, 'ICN100002', '987654321', '987654321', 'None', 'Verified', 'N', 'N', 50, '1975-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'Female', 'Muslim', 2, 'Married', 2, NULL, 1002, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(110011003, 'IEN100003', 508, 'Carol Soolaa', 'Soola', 'Carol', 'N', 'N', 'Y', 'Regular', 101, 'ICN100003', '111111111', '111111111', 'None', 'Verified', 'N', 'N', 35, '1990-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'Female', 'Muslim', 2, 'Married', 2, NULL, 1002, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(110011004, 'IEN100004', 508, 'Debby Tiidoo', 'Tiidoo', 'Debby', 'N', 'N', 'Y', 'Regular', 101, 'ICN100004', '111112222', '111112222', 'None', 'Verified', 'N', 'N', 71, '1954-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', 'Female', 'Muslim', 2, 'Married', 2, NULL, 1002, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(110011005, 'IEN100005', 516, 'Adam Amajor', 'Amajor', 'Adam', 'N', 'N', 'Y', 'Regular', 101, 'ICN100005', '111221001', '111221001', 'None', 'Verified', 'N', 'N', 85, '1940-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'M', 'Male', 'Christian', 2, 'Married', 2, NULL, 1002, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-01-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),

(110011006, 'IEN100006', 516, 'Barry Bmajor', 'Bmajor', 'Barry', 'N', 'N', 'Y', 'Regular', 101, 'ICN100006', '111221002', '111221002', 'None', 'Verified', 'N', 'N', 63, '1961-01-02', NULL, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'M', 'Male', 'Christian', 2, 'Married', 2, NULL, 1002, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-02-21', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
GO
