@startuml

' ETL Workflow Sequence Diagram

participant   "User Dashboard"   as DSH #lightblue
participant   "ETL Engine"       as ETL #lightblue
participant   "DSS Database"     as DDB #lightblue
participant   "DSS File System"  as FSY #lightblue
participant   "DSR Mainframe"    as DSR

DSH ->  DSH : select site(s),\nselect extract(s),\nselect date range,\nselect "audit" or "final"
DSH ->  ETL : start ETL process
ETL ->  DDB : get raw extract data
DDB --> ETL : return raw extract data
ETL ->  ETL : transform records
ETL ->  DDB : save transformed records
ETL ->  ETL : create extract files(s)
ETL ->  FSY : save extract file(s)
ETL ->  DSR : send extract files(s) via SFTP to drop location
DSR --> ETL : return "success" or "fail" message
ETL ->  DDB : save transaction audit and log records
ETL ->  DSH : send status message

@enduml